//
// Generated file, do not edit! Created by opp_msgtool 6.0 from iov_sim/modules/messages/neighbor/NeighborBaseMessage.msg.
//

#ifndef __IOV_SIM_NEIGHBORBASEMESSAGE_M_H
#define __IOV_SIM_NEIGHBORBASEMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef IOV_SIM_API
#  if defined(IOV_SIM_EXPORT)
#    define IOV_SIM_API  OPP_DLLEXPORT
#  elif defined(IOV_SIM_IMPORT)
#    define IOV_SIM_API  OPP_DLLIMPORT
#  else
#    define IOV_SIM_API
#  endif
#endif


namespace iov_sim {

class NeighborBaseMessage;

}  // namespace iov_sim

#include "iov_sim/modules/messages/cluster/ClusterBaseMessage_m.h" // import iov_sim.modules.messages.cluster.ClusterBaseMessage


namespace iov_sim {

/**
 * Class generated from <tt>iov_sim/modules/messages/neighbor/NeighborBaseMessage.msg:27</tt> by opp_msgtool.
 * <pre>
 * packet NeighborBaseMessage extends BaseMessage
 * {
 *     string origin;
 * }
 * </pre>
 */
class IOV_SIM_API NeighborBaseMessage : public ::iov_sim::BaseMessage
{
  protected:
    ::omnetpp::opp_string origin;

  private:
    void copy(const NeighborBaseMessage& other);

  protected:
    bool operator==(const NeighborBaseMessage&) = delete;

  public:
    NeighborBaseMessage(const char *name=nullptr, short kind=0);
    NeighborBaseMessage(const NeighborBaseMessage& other);
    virtual ~NeighborBaseMessage();
    NeighborBaseMessage& operator=(const NeighborBaseMessage& other);
    virtual NeighborBaseMessage *dup() const override {return new NeighborBaseMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getOrigin() const;
    virtual void setOrigin(const char * origin);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const NeighborBaseMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, NeighborBaseMessage& obj) {obj.parsimUnpack(b);}


}  // namespace iov_sim


namespace omnetpp {

template<> inline iov_sim::NeighborBaseMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<iov_sim::NeighborBaseMessage*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __IOV_SIM_NEIGHBORBASEMESSAGE_M_H

