//
// Generated file, do not edit! Created by opp_msgtool 6.0 from iov_sim/modules/messages/model/ModelBaseMessage.msg.
//

#ifndef __IOV_SIM_MODELBASEMESSAGE_M_H
#define __IOV_SIM_MODELBASEMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef IOV_SIM_API
#  if defined(IOV_SIM_EXPORT)
#    define IOV_SIM_API  OPP_DLLEXPORT
#  elif defined(IOV_SIM_IMPORT)
#    define IOV_SIM_API  OPP_DLLIMPORT
#  else
#    define IOV_SIM_API
#  endif
#endif


namespace iov_sim {

class ModelBaseMessage;

}  // namespace iov_sim

#include "iov_sim/base/messages/BaseMessage_m.h" // import iov_sim.base.messages.BaseMessage


namespace iov_sim {

/**
 * Class generated from <tt>iov_sim/modules/messages/model/ModelBaseMessage.msg:27</tt> by opp_msgtool.
 * <pre>
 * packet ModelBaseMessage extends BaseMessage
 * {
 *     string data;
 *     string origin = "rsu";
 *     string destination;
 *     string pStateDict;
 *     string vStateDict;
 * }
 * </pre>
 */
class IOV_SIM_API ModelBaseMessage : public ::iov_sim::BaseMessage
{
  protected:
    ::omnetpp::opp_string data;
    ::omnetpp::opp_string origin = "rsu";
    ::omnetpp::opp_string destination;
    ::omnetpp::opp_string pStateDict;
    ::omnetpp::opp_string vStateDict;

  private:
    void copy(const ModelBaseMessage& other);

  protected:
    bool operator==(const ModelBaseMessage&) = delete;

  public:
    ModelBaseMessage(const char *name=nullptr, short kind=0);
    ModelBaseMessage(const ModelBaseMessage& other);
    virtual ~ModelBaseMessage();
    ModelBaseMessage& operator=(const ModelBaseMessage& other);
    virtual ModelBaseMessage *dup() const override {return new ModelBaseMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getData() const;
    virtual void setData(const char * data);

    virtual const char * getOrigin() const;
    virtual void setOrigin(const char * origin);

    virtual const char * getDestination() const;
    virtual void setDestination(const char * destination);

    virtual const char * getPStateDict() const;
    virtual void setPStateDict(const char * pStateDict);

    virtual const char * getVStateDict() const;
    virtual void setVStateDict(const char * vStateDict);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ModelBaseMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ModelBaseMessage& obj) {obj.parsimUnpack(b);}


}  // namespace iov_sim


namespace omnetpp {

template<> inline iov_sim::ModelBaseMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<iov_sim::ModelBaseMessage*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __IOV_SIM_MODELBASEMESSAGE_M_H

