//
// Generated file, do not edit! Created by opp_msgtool 6.0 from iov_sim/modules/messages/cluster/ClusterHeartbeatReplyAck.msg.
//

#ifndef __IOV_SIM_CLUSTERHEARTBEATREPLYACK_M_H
#define __IOV_SIM_CLUSTERHEARTBEATREPLYACK_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef IOV_SIM_API
#  if defined(IOV_SIM_EXPORT)
#    define IOV_SIM_API  OPP_DLLEXPORT
#  elif defined(IOV_SIM_IMPORT)
#    define IOV_SIM_API  OPP_DLLIMPORT
#  else
#    define IOV_SIM_API
#  endif
#endif


namespace iov_sim {

class ClusterHeartbeatReplyAck;

}  // namespace iov_sim

#include "iov_sim/modules/messages/cluster/ClusterBaseMessage_m.h" // import iov_sim.modules.messages.cluster.ClusterBaseMessage


namespace iov_sim {

/**
 * Class generated from <tt>iov_sim/modules/messages/cluster/ClusterHeartbeatReplyAck.msg:27</tt> by opp_msgtool.
 * <pre>
 * packet ClusterHeartbeatReplyAck extends ClusterBaseMessage
 * {
 *     string destination;
 * }
 * </pre>
 */
class IOV_SIM_API ClusterHeartbeatReplyAck : public ::iov_sim::ClusterBaseMessage
{
  protected:
    ::omnetpp::opp_string destination;

  private:
    void copy(const ClusterHeartbeatReplyAck& other);

  protected:
    bool operator==(const ClusterHeartbeatReplyAck&) = delete;

  public:
    ClusterHeartbeatReplyAck(const char *name=nullptr, short kind=0);
    ClusterHeartbeatReplyAck(const ClusterHeartbeatReplyAck& other);
    virtual ~ClusterHeartbeatReplyAck();
    ClusterHeartbeatReplyAck& operator=(const ClusterHeartbeatReplyAck& other);
    virtual ClusterHeartbeatReplyAck *dup() const override {return new ClusterHeartbeatReplyAck(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getDestination() const;
    virtual void setDestination(const char * destination);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ClusterHeartbeatReplyAck& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ClusterHeartbeatReplyAck& obj) {obj.parsimUnpack(b);}


}  // namespace iov_sim


namespace omnetpp {

template<> inline iov_sim::ClusterHeartbeatReplyAck *fromAnyPtr(any_ptr ptr) { return check_and_cast<iov_sim::ClusterHeartbeatReplyAck*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __IOV_SIM_CLUSTERHEARTBEATREPLYACK_M_H

