//
// Generated file, do not edit! Created by opp_msgtool 6.0 from iov_sim/modules/messages/cluster/ClusterHeartbeatReply.msg.
//

#ifndef __IOV_SIM_CLUSTERHEARTBEATREPLY_M_H
#define __IOV_SIM_CLUSTERHEARTBEATREPLY_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef IOV_SIM_API
#  if defined(IOV_SIM_EXPORT)
#    define IOV_SIM_API  OPP_DLLEXPORT
#  elif defined(IOV_SIM_IMPORT)
#    define IOV_SIM_API  OPP_DLLIMPORT
#  else
#    define IOV_SIM_API
#  endif
#endif


namespace iov_sim {

class ClusterHeartbeatReply;

}  // namespace iov_sim

#include "iov_sim/modules/messages/cluster/ClusterBaseMessage_m.h" // import iov_sim.modules.messages.cluster.ClusterBaseMessage


namespace iov_sim {

/**
 * Class generated from <tt>iov_sim/modules/messages/cluster/ClusterHeartbeatReply.msg:27</tt> by opp_msgtool.
 * <pre>
 * packet ClusterHeartbeatReply extends ClusterBaseMessage
 * {
 *     string destination;
 *     string nodeMobility;
 * }
 * </pre>
 */
class IOV_SIM_API ClusterHeartbeatReply : public ::iov_sim::ClusterBaseMessage
{
  protected:
    ::omnetpp::opp_string destination;
    ::omnetpp::opp_string nodeMobility;

  private:
    void copy(const ClusterHeartbeatReply& other);

  protected:
    bool operator==(const ClusterHeartbeatReply&) = delete;

  public:
    ClusterHeartbeatReply(const char *name=nullptr, short kind=0);
    ClusterHeartbeatReply(const ClusterHeartbeatReply& other);
    virtual ~ClusterHeartbeatReply();
    ClusterHeartbeatReply& operator=(const ClusterHeartbeatReply& other);
    virtual ClusterHeartbeatReply *dup() const override {return new ClusterHeartbeatReply(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getDestination() const;
    virtual void setDestination(const char * destination);

    virtual const char * getNodeMobility() const;
    virtual void setNodeMobility(const char * nodeMobility);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ClusterHeartbeatReply& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ClusterHeartbeatReply& obj) {obj.parsimUnpack(b);}


}  // namespace iov_sim


namespace omnetpp {

template<> inline iov_sim::ClusterHeartbeatReply *fromAnyPtr(any_ptr ptr) { return check_and_cast<iov_sim::ClusterHeartbeatReply*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __IOV_SIM_CLUSTERHEARTBEATREPLY_M_H

