//
// Generated file, do not edit! Created by opp_msgtool 6.0 from iov_sim/modules/messages/cluster/ClusterBaseMessage.msg.
//

#ifndef __IOV_SIM_CLUSTERBASEMESSAGE_M_H
#define __IOV_SIM_CLUSTERBASEMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef IOV_SIM_API
#  if defined(IOV_SIM_EXPORT)
#    define IOV_SIM_API  OPP_DLLEXPORT
#  elif defined(IOV_SIM_IMPORT)
#    define IOV_SIM_API  OPP_DLLIMPORT
#  else
#    define IOV_SIM_API
#  endif
#endif


namespace iov_sim {

class ClusterBaseMessage;

}  // namespace iov_sim

#include "iov_sim/base/messages/BaseMessage_m.h" // import iov_sim.base.messages.BaseMessage


namespace iov_sim {

/**
 * Class generated from <tt>iov_sim/modules/messages/cluster/ClusterBaseMessage.msg:27</tt> by opp_msgtool.
 * <pre>
 * packet ClusterBaseMessage extends BaseMessage
 * {
 *     string origin;
 *     string clusterId;
 *     double timestamp;
 * }
 * </pre>
 */
class IOV_SIM_API ClusterBaseMessage : public ::iov_sim::BaseMessage
{
  protected:
    ::omnetpp::opp_string origin;
    ::omnetpp::opp_string clusterId;
    double timestamp = 0;

  private:
    void copy(const ClusterBaseMessage& other);

  protected:
    bool operator==(const ClusterBaseMessage&) = delete;

  public:
    ClusterBaseMessage(const char *name=nullptr, short kind=0);
    ClusterBaseMessage(const ClusterBaseMessage& other);
    virtual ~ClusterBaseMessage();
    ClusterBaseMessage& operator=(const ClusterBaseMessage& other);
    virtual ClusterBaseMessage *dup() const override {return new ClusterBaseMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getOrigin() const;
    virtual void setOrigin(const char * origin);

    virtual const char * getClusterId() const;
    virtual void setClusterId(const char * clusterId);

    virtual double getTimestamp() const;
    virtual void setTimestamp(double timestamp);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ClusterBaseMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ClusterBaseMessage& obj) {obj.parsimUnpack(b);}


}  // namespace iov_sim


namespace omnetpp {

template<> inline iov_sim::ClusterBaseMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<iov_sim::ClusterBaseMessage*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __IOV_SIM_CLUSTERBASEMESSAGE_M_H

