//
// Generated file, do not edit! Created by opp_msgtool 6.0 from iov_sim/modules/messages/election/ElectionTimeout.msg.
//

#ifndef __IOV_SIM_ELECTIONTIMEOUT_M_H
#define __IOV_SIM_ELECTIONTIMEOUT_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef IOV_SIM_API
#  if defined(IOV_SIM_EXPORT)
#    define IOV_SIM_API  OPP_DLLEXPORT
#  elif defined(IOV_SIM_IMPORT)
#    define IOV_SIM_API  OPP_DLLIMPORT
#  else
#    define IOV_SIM_API
#  endif
#endif


namespace iov_sim {

class ElectionTimeout;

}  // namespace iov_sim

#include "iov_sim/modules/messages/election/ElectionBaseMessage_m.h" // import iov_sim.modules.messages.election.ElectionBaseMessage


namespace iov_sim {

/**
 * Class generated from <tt>iov_sim/modules/messages/election/ElectionTimeout.msg:27</tt> by opp_msgtool.
 * <pre>
 * packet ElectionTimeout extends ElectionBaseMessage
 * {
 * }
 * </pre>
 */
class IOV_SIM_API ElectionTimeout : public ::iov_sim::ElectionBaseMessage
{
  protected:

  private:
    void copy(const ElectionTimeout& other);

  protected:
    bool operator==(const ElectionTimeout&) = delete;

  public:
    ElectionTimeout(const char *name=nullptr, short kind=0);
    ElectionTimeout(const ElectionTimeout& other);
    virtual ~ElectionTimeout();
    ElectionTimeout& operator=(const ElectionTimeout& other);
    virtual ElectionTimeout *dup() const override {return new ElectionTimeout(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ElectionTimeout& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ElectionTimeout& obj) {obj.parsimUnpack(b);}


}  // namespace iov_sim


namespace omnetpp {

template<> inline iov_sim::ElectionTimeout *fromAnyPtr(any_ptr ptr) { return check_and_cast<iov_sim::ElectionTimeout*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __IOV_SIM_ELECTIONTIMEOUT_M_H

