//
// Generated file, do not edit! Created by opp_msgtool 6.0 from iov_sim/modules/messages/election/ElectionBaseMessage.msg.
//

#ifndef __IOV_SIM_ELECTIONBASEMESSAGE_M_H
#define __IOV_SIM_ELECTIONBASEMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef IOV_SIM_API
#  if defined(IOV_SIM_EXPORT)
#    define IOV_SIM_API  OPP_DLLEXPORT
#  elif defined(IOV_SIM_IMPORT)
#    define IOV_SIM_API  OPP_DLLIMPORT
#  else
#    define IOV_SIM_API
#  endif
#endif


namespace iov_sim {

class ElectionBaseMessage;

}  // namespace iov_sim

#include "iov_sim/base/messages/BaseMessage_m.h" // import iov_sim.base.messages.BaseMessage


namespace iov_sim {

/**
 * Class generated from <tt>iov_sim/modules/messages/election/ElectionBaseMessage.msg:27</tt> by opp_msgtool.
 * <pre>
 * packet ElectionBaseMessage extends BaseMessage
 * {
 *     string origin;
 *     string destination = "";
 * }
 * </pre>
 */
class IOV_SIM_API ElectionBaseMessage : public ::iov_sim::BaseMessage
{
  protected:
    ::omnetpp::opp_string origin;
    ::omnetpp::opp_string destination = "";

  private:
    void copy(const ElectionBaseMessage& other);

  protected:
    bool operator==(const ElectionBaseMessage&) = delete;

  public:
    ElectionBaseMessage(const char *name=nullptr, short kind=0);
    ElectionBaseMessage(const ElectionBaseMessage& other);
    virtual ~ElectionBaseMessage();
    ElectionBaseMessage& operator=(const ElectionBaseMessage& other);
    virtual ElectionBaseMessage *dup() const override {return new ElectionBaseMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getOrigin() const;
    virtual void setOrigin(const char * origin);

    virtual const char * getDestination() const;
    virtual void setDestination(const char * destination);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ElectionBaseMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ElectionBaseMessage& obj) {obj.parsimUnpack(b);}


}  // namespace iov_sim


namespace omnetpp {

template<> inline iov_sim::ElectionBaseMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<iov_sim::ElectionBaseMessage*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __IOV_SIM_ELECTIONBASEMESSAGE_M_H

