//
// Generated file, do not edit! Created by opp_msgtool 6.0 from iov_sim/modules/messages/election/Election.msg.
//

#ifndef __IOV_SIM_ELECTION_M_H
#define __IOV_SIM_ELECTION_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef IOV_SIM_API
#  if defined(IOV_SIM_EXPORT)
#    define IOV_SIM_API  OPP_DLLEXPORT
#  elif defined(IOV_SIM_IMPORT)
#    define IOV_SIM_API  OPP_DLLIMPORT
#  else
#    define IOV_SIM_API
#  endif
#endif


namespace iov_sim {

class Election;

}  // namespace iov_sim

#include "iov_sim/modules/messages/election/ElectionBaseMessage_m.h" // import iov_sim.modules.messages.election.ElectionBaseMessage


namespace iov_sim {

/**
 * Class generated from <tt>iov_sim/modules/messages/election/Election.msg:27</tt> by opp_msgtool.
 * <pre>
 * packet Election extends ElectionBaseMessage
 * {
 *     string nodeMobility;
 * }
 * </pre>
 */
class IOV_SIM_API Election : public ::iov_sim::ElectionBaseMessage
{
  protected:
    ::omnetpp::opp_string nodeMobility;

  private:
    void copy(const Election& other);

  protected:
    bool operator==(const Election&) = delete;

  public:
    Election(const char *name=nullptr, short kind=0);
    Election(const Election& other);
    virtual ~Election();
    Election& operator=(const Election& other);
    virtual Election *dup() const override {return new Election(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getNodeMobility() const;
    virtual void setNodeMobility(const char * nodeMobility);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Election& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Election& obj) {obj.parsimUnpack(b);}


}  // namespace iov_sim


namespace omnetpp {

template<> inline iov_sim::Election *fromAnyPtr(any_ptr ptr) { return check_and_cast<iov_sim::Election*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __IOV_SIM_ELECTION_M_H

