//
// Generated file, do not edit! Created by opp_msgtool 6.0 from iov_sim/ApplicationLayerTestMessage.msg.
//

#ifndef __IOV_SIM_APPLICATIONLAYERTESTMESSAGE_M_H
#define __IOV_SIM_APPLICATIONLAYERTESTMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef IOV_SIM_API
#  if defined(IOV_SIM_EXPORT)
#    define IOV_SIM_API  OPP_DLLEXPORT
#  elif defined(IOV_SIM_IMPORT)
#    define IOV_SIM_API  OPP_DLLIMPORT
#  else
#    define IOV_SIM_API
#  endif
#endif


namespace iov_sim {

class ApplicationLayerTestMessage;

}  // namespace iov_sim

#include "veins/base/utils/Coord_m.h" // import veins.base.utils.Coord

#include "veins/modules/messages/BaseFrame1609_4_m.h" // import veins.modules.messages.BaseFrame1609_4

#include "veins/base/utils/SimpleAddress_m.h" // import veins.base.utils.SimpleAddress


namespace iov_sim {

/**
 * Class generated from <tt>iov_sim/ApplicationLayerTestMessage.msg:29</tt> by opp_msgtool.
 * <pre>
 * packet ApplicationLayerTestMessage extends veins::BaseFrame1609_4
 * {
 *     string demoData;
 *     veins::LAddress::L2Type senderAddress = -1;
 *     int serial = 0;
 * }
 * </pre>
 */
class IOV_SIM_API ApplicationLayerTestMessage : public ::veins::BaseFrame1609_4
{
  protected:
    ::omnetpp::opp_string demoData;
    ::veins::LAddress::L2Type senderAddress = -1;
    int serial = 0;

  private:
    void copy(const ApplicationLayerTestMessage& other);

  protected:
    bool operator==(const ApplicationLayerTestMessage&) = delete;

  public:
    ApplicationLayerTestMessage(const char *name=nullptr, short kind=0);
    ApplicationLayerTestMessage(const ApplicationLayerTestMessage& other);
    virtual ~ApplicationLayerTestMessage();
    ApplicationLayerTestMessage& operator=(const ApplicationLayerTestMessage& other);
    virtual ApplicationLayerTestMessage *dup() const override {return new ApplicationLayerTestMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getDemoData() const;
    virtual void setDemoData(const char * demoData);

    virtual const ::veins::LAddress::L2Type& getSenderAddress() const;
    virtual ::veins::LAddress::L2Type& getSenderAddressForUpdate() { return const_cast<::veins::LAddress::L2Type&>(const_cast<ApplicationLayerTestMessage*>(this)->getSenderAddress());}
    virtual void setSenderAddress(const ::veins::LAddress::L2Type& senderAddress);

    virtual int getSerial() const;
    virtual void setSerial(int serial);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ApplicationLayerTestMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ApplicationLayerTestMessage& obj) {obj.parsimUnpack(b);}


}  // namespace iov_sim


namespace omnetpp {

template<> inline iov_sim::ApplicationLayerTestMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<iov_sim::ApplicationLayerTestMessage*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __IOV_SIM_APPLICATIONLAYERTESTMESSAGE_M_H

